server:
  port: 8989


spring:
  application:
    name: cache #指定服务名
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/backend_db?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
#
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

caffeine:
  init: 100
  max: 10000